# This workflow will install Node dependencies, run tests and lint with a single version of Node


name: Build LetsEat Executable

on:
  push:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Build LetsEat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Build LetsEat
        run: npm run build

      - name: Upload build folder as asset
        uses: actions/upload-artifact@v3
        with:
          path: build
          name: LetsEat
