name: Lint Project Files

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    name: Lint LetsEat
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Run Eslint
        uses: wearerequired/lint-action@v1
        with:
          eslint: true
          eslint_args: "--max-warnings 0"
          eslint_extensions: ts
          prettier: true
          prettier_extensions: ts
          continue_on_error: false
          check_name: "${linter} ${dir}"
