name: Run tests

on:
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres_integration_test_db

jobs:
  unit:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

  integration:
    name: Run integration tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres_integration_test_db

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.13.0

      - name: Install dependencies
        run: npm install

      - name: Push Prisma schema
        run: npx prisma db push

      - name: Run Tests
        run: npm run integration
